name: Gradle Cache
description: Gradle Home Cache

inputs: 
  path:
    description: "File to save"
    required: true
outputs:
  cache-hit:
    description: "signifies if cache was hit"
    value: ${{ steps.cache_hit.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - id: cache_hit
      uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
      with:
        path: ${{ inputs.path }}
        key: value808119-${{ inputs.path }}
