on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Cache Bug

jobs:
  recreate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions
        id: folder1
        with:
          path: './folder1/file_mod'

      - name: Create file if cache was not saved and get file size
        if: steps.folder1.outputs.cache-hit != 'true'
        working-directory: folder1
        run: ./file.sh && wc -c file_mod

      - name: Get cached file size to check if it correlates with above step
        if: steps.folder1.outputs.cache-hit == 'true'
        working-directory: folder1
        run: wc -c file_mod

      - name: Store cache using a different ID
        id: folder2
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
        with:
          path: ./folder2/file_mod
          key: value8081190000-./folder2/file_mod

      - name: Create file if cache was not saved
        working-directory: folder2
        if: steps.folder2.outputs.cache-hit != 'true'
        run: ./file.sh && wc -c file_mod

      - name: Get retrieved file size
        if: steps.folder2.outputs.cache-hit == 'true'
        working-directory: folder2
        run: wc -c file_mod
