on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Cache Bug

jobs:
  recreate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions
        id: folder1
        with:
          path: './folder1/file_mod.sh'

      - name: Create file if cache was not saved
        if: steps.folder1.outputs.cache-hit != 'true'
        working-directory: folder1
        run: RUNNER=1000 ./file.sh

      - uses: ./.github/actions
        id: folder2
        with:
          path: './folder2/file_mod.sh'

      - name: Create file if cache was not saved
        working-directory: folder2
        if: steps.folder2.outputs.cache-hit != 'true'
        run: RUNNER=10000 ./file.sh

      - uses: ./.github/actions
        id: folder3
        with:
          path: './folder3/file_mod.sh'

      - name: Create file if cache was not saved
        working-directory: folder3
        if: steps.folder3.outputs.cache-hit != 'true'
        run: RUNNER=100000 ./file.sh
